# This workflow will install Python dependencies, run tests, and lint with a single version of Python
# For more information, see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --max-line-length=127 --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Black is run in a separate workflow
        
    - name: Test with pytest
      run: |
        pytest

    - name: Upload coverage to Codecov.io
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  badges:
    runs-on: ubuntu-latest

    needs: build
    if: always()  # Run the badges job even if the build job fails - we want the badges to reflect that

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up GitHub Actions Badges
      run: |
        echo "[![Build Status](https://github.com/${{ github.repository }}/workflows/Python%20CI/badge.svg)](https://github.com/${{ github.repository }}/actions?query=workflow%3A%22Python+CI%22)" >> README.md
        echo "[![codecov](https://codecov.io/gh/${{ github.repository }}/main/graph/badge.svg)](https://codecov.io/gh/${{ github.repository }}/main)" >> README.md
        echo "[![Flake8](https://img.shields.io/badge/flake8-checked-blue)](https://flake8.pycqa.org/en/latest/)" >> README.md
        
